### ISSUE TITLE
How to make new edits on atlas?

### ISSUE THREAD

**Issue by sydney0zq** [ykasten/layered-neural-atlases#10]
Hello thanks for your amazing work.

I have run the train and edit based on your pretrained model, everything goes fine.

However, after I train 40w model on blackswan and use your edited altas, I cannot get correct results. Should I make new atlas images based on the new trained model? Then where I could get the raw atlas(unedit from the model) images?

Thanks in advance.

**Comment by ykasten** [comment]
Apply an empty edit (a zeros image with zero alpha channel) to your trained model. The discretized version of your atlas can be found in the result folder. This atlas can now be edited, or an edit layer can be added to it.
